; platformio.ini - Firmware de la CYD (ESP32-2432S028R)
; Sesion 6: lee el tactil XPT2046 y envia (x,y) al S3 por UART. NO pinta pantalla.

[env:cyd]
platform      = espressif32
board         = esp32dev          ; la CYD lleva un ESP32-WROOM (no S3), 4 MB flash
framework     = arduino
monitor_speed = 115200

; Libreria del tactil resistivo XPT2046. PlatformIO la descarga sola al compilar;
; no hay que instalar nada a mano ni tocar User_Setup.h (eso es de TFT_eSPI, que
; aqui no usamos).
lib_deps =
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
